apiVersion: v1
kind: Pod
metadata:
  name: my-app
spec:
  containers:
  - name: my-app
    image: crackitty/nginx-webbapp:1.0
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
        ephemeral-storage: 50Mi
    ports:
      - containerPort: 80
